name: Exemplo CI

on:
  push:
  pull_request:

jobs:
  executar-javascript:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar o código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24"

      - name: Executar testes
        run: npm test

      - name: Verificar variável secreta
        env:
          MINHA_CHAVE: ${{ secrets.MINHA_CHAVE }}
        run: |
          if [ -n "$MINHA_CHAVE" ]; then
            echo "Variável secreta configurada corretamente"
          else
            echo "Variável secreta não encontrada"
            exit 1
          fi
          

